const N = Date.now();

const mockContratos = [
  {
    address: "0xc001",
    no: "DS01",
    type: "contract",
    title: "Diseña la identidad visual de mi cafetería",
    category: "Diseño & Creatividad",
    bounty: 1200,
    status: "open",
    isPrivate: false,
    expiresAt: N + 432000000,
    participants: 4,
    creator: "0xabc1",
    description:
      "Necesito logotipo SVG+PNG, paleta de colores, tipografía y mockup en vaso.",
  },
  {
    address: "0xc002",
    no: "TK02",
    type: "contract",
    title: "Arregla el bug de paginación en mi app React",
    category: "Tecnología & Dev",
    bounty: 350,
    status: "open",
    isPrivate: false,
    expiresAt: N + 172800000,
    participants: 2,
    creator: "0xabc2",
    description:
      "El componente Paginator falla cuando totalItems < pageSize. Entregar PR con fix y tests.",
  },
  {
    address: "0xc003",
    no: "HR03",
    type: "contract",
    title: "Pinta el salón y el pasillo de mi apartamento",
    category: "Hogar & Reparaciones",
    bounty: 680,
    status: "pending",
    isPrivate: false,
    expiresAt: N + 259200000,
    participants: 3,
    creator: "0xabc3",
    description:
      "Superficie aprox. 45m². Dos manos de pintura, recogida de materiales y limpieza final.",
  },
  {
    address: "0xc004",
    no: "WR04",
    type: "contract",
    title: "Escribe el discurso para mi boda (10 minutos)",
    category: "Escritura & Contenido",
    bounty: 200,
    status: "open",
    isPrivate: false,
    expiresAt: N + 604800000,
    participants: 1,
    creator: "0xabc4",
    description:
      "Tono emotivo-humorístico, 3 anécdotas reales, máximo 900 palabras.",
  },
  {
    address: "0xc005",
    no: "MK05",
    type: "contract",
    title: "Gestiona mis redes sociales durante agosto",
    category: "Marketing & Redes",
    bounty: 900,
    status: "open",
    isPrivate: false,
    expiresAt: N + 86400000,
    participants: 6,
    creator: "0xabc5",
    description:
      "Instagram + TikTok. 20 posts mensuales, copywriting incluido, métricas al cierre.",
  },
  {
    address: "0xc006",
    no: "LG06",
    type: "contract",
    title: "Revisa mi contrato de arrendamiento comercial",
    category: "Legal & Finanzas",
    bounty: 500,
    status: "open",
    isPrivate: true,
    expiresAt: N + 172800000,
    participants: 2,
    creator: "0xabc6",
    description:
      "Identificar cláusulas abusivas y redactar 5 recomendaciones concretas.",
  },
  {
    address: "0xc007",
    no: "TK07",
    type: "contract",
    title: "Crea un chatbot de soporte para mi tienda online",
    category: "Tecnología & Dev",
    bounty: 2400,
    status: "cancelled",
    isPrivate: false,
    expiresAt: N - 7200000,
    participants: 0,
    creator: "0xabc7",
    description:
      "Integración con WhatsApp Business API. Flujos para pedidos, devoluciones y horarios.",
  },
  // Cívicos
  {
    address: "0xcv01",
    no: "CV01",
    type: "civic",
    title: "Municipio propone renovación del Parque Central",
    category: "Infraestructura",
    bounty: 50000,
    status: "open",
    isPrivate: false,
    expiresAt: N + 1209600000,
    participants: 142,
    creator: "0xgov1",
    description:
      "El Municipio de San Rafael ha depositado $50,000 para la renovación del Parque Central. Los fondos irán a Constructora Verde S.A. si la comunidad aprueba.",
    votesYes: 98,
    votesNo: 44,
    destinationAddress: "0xconst1",
  },
  {
    address: "0xcv02",
    no: "CV02",
    type: "civic",
    title: "Fundación propone biblioteca digital comunitaria",
    category: "Educación",
    bounty: 12000,
    status: "pending",
    isPrivate: false,
    expiresAt: N + 604800000,
    participants: 67,
    creator: "0xgov2",
    description:
      "Fundación Saber Digital ha depositado $12,000 para implementar una biblioteca digital. Los fondos irán a TechEdu LATAM si hay consenso.",
    votesYes: 51,
    votesNo: 16,
    destinationAddress: "0xteched1",
  },
];

const mockApuestas = [
  {
    address: "0xb001",
    no: "AP01",
    type: "bet",
    title: "¿Gana Ecuador el próximo partido clasificatorio?",
    category: "Deportes",
    status: "open",
    isPrivate: false,
    expiresAt: N + 172800000,
    participants: 31,
    creator: "0xbet1",
    betStruct: "binary",
    sides: [
      { label: "SÍ — Gana", pool: 1840, participants: 19, color: "#1a5c34" },
      { label: "NO — No gana", pool: 960, participants: 12, color: "#8b1a2a" },
    ],
  },
  {
    address: "0xb002",
    no: "AP02",
    type: "bet",
    title: "¿Cuánto varía el tipo de cambio USD/EUR esta semana?",
    category: "Finanzas & Mercados",
    status: "open",
    isPrivate: false,
    expiresAt: N + 432000000,
    participants: 18,
    creator: "0xbet2",
    betStruct: "multi",
    sides: [
      { label: "Sube > 1%", pool: 620, participants: 7, color: "#1a5c34" },
      { label: "Varía ±1%", pool: 940, participants: 9, color: "#8a6c1a" },
      { label: "Baja > 1%", pool: 310, participants: 4, color: "#8b1a2a" },
    ],
  },
  {
    address: "0xb003",
    no: "AP03",
    type: "bet",
    title: "¿Qué película gana el próximo Óscar a Mejor Película?",
    category: "Entretenimiento",
    status: "open",
    isPrivate: false,
    expiresAt: N + 1209600000,
    participants: 44,
    creator: "0xbet3",
    betStruct: "multi",
    sides: [
      {
        label: "Favorita de críticos",
        pool: 1200,
        participants: 15,
        color: "#1a3254",
      },
      { label: "La revelación", pool: 880, participants: 11, color: "#5c1e7a" },
      { label: "El blockbuster", pool: 540, participants: 8, color: "#923210" },
      {
        label: "La propuesta indie",
        pool: 380,
        participants: 10,
        color: "#1a5c34",
      },
    ],
  },
  {
    address: "0xb004",
    no: "AP04",
    type: "bet",
    title: "¿Aprobará Camila el examen de conducir al primer intento?",
    category: "Vida cotidiana",
    status: "pending",
    isPrivate: false,
    expiresAt: N + 86400000,
    participants: 12,
    creator: "0xbet4",
    betStruct: "binary",
    sides: [
      { label: "SÍ — Aprueba", pool: 420, participants: 8, color: "#1a5c34" },
      { label: "NO — Repite", pool: 180, participants: 4, color: "#8b1a2a" },
    ],
  },
  {
    address: "0xb005",
    no: "AP05",
    type: "bet",
    title: "¿Llega el paquete de Arturo antes del jueves?",
    category: "Vida cotidiana",
    status: "open",
    isPrivate: true,
    expiresAt: N + 259200000,
    participants: 8,
    creator: "0xbet5",
    betStruct: "binary",
    sides: [
      { label: "SÍ — Llega", pool: 150, participants: 5, color: "#1a5c34" },
      { label: "NO — Se retrasa", pool: 90, participants: 3, color: "#8b1a2a" },
    ],
  },
];

// Calcula el pool total de una apuesta
function calcTotalPool(sides) {
  return sides.reduce((s, sd) => s + sd.pool, 0);
}

// Agrega campo totalPool a cada apuesta
const mockApuestasNormalizadas = mockApuestas.map((a) => ({
  ...a,
  totalPool: calcTotalPool(a.sides),
}));

module.exports = { mockContratos, mockApuestas: mockApuestasNormalizadas };
